### ISSUE TITLE
Add new hardware columns

### ISSUE THREAD

**Issue by Vrv18** [cloud-gpus/cloud-gpus.github.io#15]
Similar to [Add new providers](https://github.com/cloud-gpus/cloud-gpus.github.io/issues/3) for more hardware options.

Consider H100

**Comment by hcarlens** [comment]
Will be added shortly.

**Comment by hcarlens** [comment]
4090 and H100 are visible on the front-end now. Many providers still have a waitlist for H100, without public pricing.
