### ISSUE TITLE
What about AIME GPU Cloud?

### ISSUE THREAD

**Issue by headkit** [cloud-gpus/cloud-gpus.github.io#23]
What about [AIME GPU Cloud](https://www.aime.info/gpucloud/)?

**Comment by hcarlens** [comment]
Thanks, I'll review this. Are you affiliated with AIME?

**Comment by headkit** [comment]
Yes, I am involved.

**Comment by hcarlens** [comment]
Apologies for going quiet on this issue. I'm open to listing AIME, but I'd like to check a few things first - could you or someone from your team please email [verify@cloud-gpus.com](mailto:verify@cloud-gpus.com)? Closing this issue for now.
