### ISSUE TITLE
Add new providers

### ISSUE THREAD

**Issue by hcarlens** [cloud-gpus/cloud-gpus.github.io#3]
Consider adding FluidStack and CoreWeave.

**Comment by hcarlens** [comment]
Added CoreWeave. Should also look at Vultr and Linode.

**Comment by hcarlens** [comment]
And OVH.

**Comment by hcarlens** [comment]
Added OVH, Linode, and Vultr: https://github.com/cloud-gpus/cloud-gpus.github.io/commit/1d4ed57bb85fefeca7537334d9ab96b17968f95e. 
Still need to look into FluidStack

**Comment by hcarlens** [comment]
Added FluidStack. Consider adding Scaleway: https://www.scaleway.com/en/

**Comment by BrianPulfer** [comment]
Please consider adding [HuggingFace's new DGX Cloud](https://huggingface.co/blog/train-dgx-cloud).

[NVIDIA L40S](https://www.nvidia.com/en-us/data-center/l40/)	48GB	$2.75/h
[NVIDIA H100](https://www.nvidia.com/de-de/data-center/h100/)	80 GB	$8.25/h

**Comment by hcarlens** [comment]
Thanks! 

I would like to check a few things before adding these providers. 

@annapeshekhon, could you please ask someone from the team at Nebius to email verify@cloud-gpus.com? 

@BrianPulfer, currently cloud-gpus.com only includes providers that offer GPU VMs, and (I think?) HuggingFace's offering is a layer above that. If I've misinterpreted that, please ask someone from the HF DGX Cloud team to email verify@cloud-gpus.com and I'll take it from there.

**Comment by thundergolfer** [comment]
Hey @hcarlens would you consider GPU containers as valid? I arrived on your website from [a Jeremy Howard blog post](https://www.answer.ai/posts/2024-03-06-fsdp-qlora.html#fnref1) and wanted to include https://modal.com/pricing gpus.

Modal doesn't offer VMs. It's a serverless platform which runs containers (gVisor).
